apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  username: pgadmin
  password: MyP@ssword123
  url: jdbc:postgresql://mypgserveranuj123.postgres.database.azure.com:5432/helloappdb